# Generated by Django 5.1.6 on 2025-02-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hotel_photo_tour_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='branch',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='main/hotelphotos/', verbose_name='Фото отеля'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='main/tourphotos/', verbose_name='Фото тура'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
