# Generated by Django 5.1.6 on 2025-02-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_employee_branch_alter_hotel_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='departure_city',
        ),
    ]
